### ISSUE TITLE
Error with sanic

### ISSUE THREAD

**Issue by nadirzebiri** [solero/dash#33]
Getting this error with Dash. Result: Unable to create a club penguin account

2023-04-11 15:56:05 Traceback (most recent call last):
2023-04-11 15:56:05   File "/usr/src/dash/bootstrap.py", line 3, in <module>
2023-04-11 15:56:05     from sanic.log import logger
2023-04-11 15:56:05   File "/usr/local/lib/python3.11/site-packages/sanic/init.py", line 2, in <module>
2023-04-11 15:56:05     from sanic.app import Sanic
2023-04-11 15:56:05   File "/usr/local/lib/python3.11/site-packages/sanic/app.py", line 102, in <module>
2023-04-11 15:56:05     from sanic.server.protocols.websocket_protocol import WebSocketProtocol
2023-04-11 15:56:05   File "/usr/local/lib/python3.11/site-packages/sanic/server/protocols/websocket_protocol.py", line 3, in <module>
2023-04-11 15:56:05     from websockets.connection import CLOSED, CLOSING, OPEN
2023-04-11 15:56:05 ImportError: cannot import name 'CLOSED' from 'websockets.connection' (/usr/local/lib/python3.11/site-packages/websockets/connection.py)
2023-04-11 15:56:05 2023/04/11 19:56:05 Command exited with error: exit status 1

**Comment by AllinolCP** [comment]
might consider using python <3.11 and using the version of sanic specified in requirements.txt

**Comment by nadirzebiri** [comment]
I haven't set anything up. I've used Wand. Could the error come from there ?

**Comment by AceCookies** [comment]
Same for me following a reset of Ubuntu....

I'm not sure what could dix that.
