### ISSUE TITLE
Error with Sanic (need more help)

### ISSUE THREAD

**Issue by nadirzebiri** [solero/dash#34]
So I have downgraded the Python version of Dash (replaced `FROM python:3-alpine` for `FROM python:3-10-alpine` in Dockerfile and rebuilt the image).

![image](https://user-images.githubusercontent.com/115375151/231599890-ab778585-72ce-4fca-8d57-6e6b1be52cff.png)

And I still get the same error
```
dash_1               | Traceback (most recent call last):
dash_1               |   File "/usr/src/dash/bootstrap.py", line 3, in <module>
dash_1               |     from sanic.log import logger
dash_1               |   File "/usr/local/lib/python3.10/site-packages/sanic/__init__.py", line 2, in <module>
dash_1               |     from sanic.app import Sanic
dash_1               |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 102, in <module>
dash_1               |     from sanic.server.protocols.websocket_protocol import WebSocketProtocol
dash_1               |   File "/usr/local/lib/python3.10/site-packages/sanic/server/protocols/websocket_protocol.py", line 3, in <module>
dash_1               |     from websockets.connection import CLOSED, CLOSING, OPEN
dash_1               | ImportError: cannot import name 'CLOSED' from 'websockets.connection' (/usr/local/lib/python3.10/site-packages/websockets/connection.py)
dash_1               | 2023/04/12 22:10:22 Command exited with error: exit status 1
```

Thanks for investigating,

**Comment by AllinolCP** [comment]
fixed in latest commit

**Comment by nadirzebiri** [comment]
Thanks I can confirm that it works now
